### ISSUE TITLE
Archivo del modulo de nomina pendiente migrar "salary_rule_data.xml"

### ISSUE THREAD

**Issue by NicolasOT** [Vauxoo/osmexico#7]
Saludos equipo,

En las pruebas en la instancia Staging v.17 se reporta el siguiente error al momento de generar un recibo de nomina.

![image](https://github.com/Vauxoo/osmexico/assets/112537218/46361225-6547-4407-be98-800674d9183d)

Pasos para replicar:

1. Ingresar al modulo de nomina
2.  Ingresar a la ruta Recibos de nómina -> Lotes
3.  Colocar fechas Periodo y pago
4. "Generar recibo de nómina" 
5.  Seleccionar estructura salaria "Nomina"
6. Agregar empleados
7. "Generar"

Comentarios de Luis Torres:

El problema se esta debiendo a que el archivo "Salary_rule_data.xml" no esta actualizado a la v.17 en la instancia del cliente
https://git.vauxoo.com/vauxoo/osmexico/-/blob/17.0/osmexico/data/salary_rule_data.xml?ref_type=heads

URL TAREA: https://www.vauxoo.com/web#id=81017&cids=1&menu_id=1490&action=1928&model=project.task&view_type=form

**Comment by desdelinux** [comment]
Hola @xmglord me puedes ayudar con esto.

**Comment by luistorresm** [comment]
Hello @xmglord 

This will be fixed with some like [this](https://git.vauxoo.com/vauxoo/l10n-mx-payroll/-/commit/81a4d4e6ce7b068b2d0aa3728ccfa7202b830037#9f7f00b6be31fb84edeaf4c53fa43761350e2ac5_15_15),

Regards

**Comment by xmglord** [comment]
This is being solved in [this MR](https://git.vauxoo.com/vauxoo/osmexico/-/merge_requests/9).

FYI @NicolasOT issues should be reported in [Gitlab](https://git.vauxoo.com/vauxoo/osmexico/-/issues).
